

java_library(
  name = "common",
  srcs = [
    "FileUtils.java",
  ],
  deps = [
    "//third_party/maven/com/google/code/findbugs:jsr305",
    "//third_party/maven/com/google/guava:guava",
    "//third_party/maven/com/google/protobuf:protobuf_java",
    "//third_party/maven/org/apache/commons:commons_lang3",
  ]
)
