package(default_visibility = ["//visibility:public"])

java_test(
    name = "line_number_converter_test",
    srcs = [
        "LineNumberConverterTest.java",
    ],
    local = 1,
    test_class = "com.google.startupos.tools.reviewer.job.sync.tests.LineNumberConverterTest",
    deps = [
        "//common",
        "//third_party/maven/junit",
        "//tools/reviewer/job/sync:github_sync",
    ],
)
